apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-container
        # image: <your-dockerhub-username>/hello-world-app:v1
        image: mdnazmulhossain/hello-world-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
