apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  labels:
    type: locak
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: media-pvc
  
