apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  labels: 
    name:  media-pvc
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/media-pv