apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-container
        image: YOUR_DOCKERHUB_USERNAME/YOUR_IMAGE_NAME:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: django-postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: YOUR_DATABASE_NAME
        - name: DATABASE_USER
          value: YOUR_POSTGRES_USER
        - name: DATABASE_PASSWORD
          value: YOUR_POSTGRES_PASSWORD
      - name: postgres-container
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: YOUR_DATABASE_NAME
        - name: POSTGRES_USER
          value: YOUR_POSTGRES_USER
        - name: POSTGRES_PASSWORD
          value: YOUR_POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
