services:
  # dbb:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  projectb:
    build: .
    command: ./shell.sh
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8051:8051"
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    # depends_on:
    #   - dbb
    
  queueb:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumers.py'
    # depends_on:
    #   - dbb